name: viddet-mx
channels:
  - conda-forge

dependencies:
  - python==3.6.3
  - pip
  - matplotlib
  - pip:
      - mxnet-cu100
      - gluoncv
      - tensorflow-gpu==2.0.0a0
      - opencv-python==4.0.0.21
      - tqdm
      - requests
      - eventlet
      - lxml
      - Pillow
      - contextlib2
      - nltk
      - absl-py
      - tensorboardX